# Generated by Django 4.0.5 on 2022-07-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('titolo', models.CharField(max_length=200)),
                ('data_pub', models.DateField(default=None)),
                ('cover', models.ImageField(default='/imgs/missing_album.jpg', upload_to='covers/')),
                ('titolo_autore', models.CharField(error_messages={'invalid': 'Esiste già'}, max_length=600, primary_key=True, serialize=False)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('titolo', models.CharField(max_length=200)),
                ('durata', models.DurationField()),
                ('data_pub', models.DateField(default=None)),
                ('visite', models.IntegerField(default=0)),
                ('testo', models.TextField(max_length=100000)),
                ('cover', models.ImageField(blank=True, default='/imgs/missing.png', null=True, upload_to='covers/')),
                ('file_visite', models.FilePathField(default=None, path='C:\\Users\\Francesco rigoni\\Documents\\tecnologie-web\\PyGenius\\static/media/logs')),
                ('popolarità', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('titolo_autore', models.CharField(error_messages={'invalid': 'Esiste già'}, max_length=600, primary_key=True, serialize=False)),
                ('album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canzoni', to='gestione.album')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canzoni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Canzoni',
            },
        ),
        migrations.CreateModel(
            name='Contributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(default=None)),
                ('data_post', models.DateField(default=None)),
                ('posizione', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('ha_star', models.BooleanField(default=False)),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='gestione.canzone')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contributi',
            },
        ),
    ]
