# Generated by Django 4.0.4 on 2022-05-13 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('durata', models.FloatField()),
                ('data_pub', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('durata', models.DurationField()),
                ('data_pub', models.DateField(default=None)),
                ('visite', models.IntegerField(default=0)),
                ('testo', models.TextField(max_length=10000)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canzoni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Canzoni',
            },
        ),
        migrations.CreateModel(
            name='Contributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_post', models.DateField(default=None)),
                ('posizione', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='gestione.canzone')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contributi',
            },
        ),
    ]
