# Generated by Django 4.0.4 on 2022-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='canzone',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
